language: node_js
node_js:
  - "5.6.0"
  - "5.5.0"
  - "4.3.1"
install:
  - npm install
  - npm install coffee-coverage istanbul coveralls
script:
  - mocha --compilers coffee:coffee-script/register --require coffee-coverage/register-istanbul --recursive tests
  - istanbul report text-summary lcov
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libfuzzy-dev

